name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          # Убрали проблемные пакеты gstreamer, которые ломали сборку
          sudo apt-get install -y --fix-missing \
            git zip unzip openjdk-17-jdk-headless autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libsqlite3-dev libgdbm-dev libssl-dev \
            libbz2-dev libffi-dev liblzma-dev libasound2-dev shared-mime-info

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33 virtualenv buildozer

      - name: Build Android APK
        run: |
          yes | buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 1

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: Kivy-App-APK
          path: bin/*.apk
