name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      # Устанавливаем системные утилиты сборки и базовый пакет лицензий Android
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
            git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libsqlite3-dev libgdbm-dev libssl-dev \
            libbz2-dev libffi-dev liblzma-dev libasound2-dev shared-mime-info

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33 virtualenv buildozer

      - name: Build Android APK
        run: |
          # Полностью очищаем все папки перед чистым запуском
          rm -rf .buildozer
          rm -rf ~/.buildozer
          
          # Запускаем сборку, Buildozer сам скачает SDK/NDK в нужные ему места
          yes | buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 1
