name: Build Kivy APK

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11.9'

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y --fix-missing \
            git zip unzip autoconf libtool pkg-config \
            zlib1g-dev libncurses5-dev libsqlite3-dev libgdbm-dev libssl-dev \
            libbz2-dev libffi-dev liblzma-dev libasound2-dev shared-mime-info

      - name: Install Python Dependencies
        run: |
          pip install --upgrade pip
          pip install Cython==0.29.33 virtualenv buildozer

      - name: Build Android APK
        run: |
          # 1. Принудительно очищаем старые папки
          rm -rf .buildozer
          
          # 2. Создаем системные папки лицензий в домашней директории Buildozer
          mkdir -p ~/.buildozer/android/platform/android-sdk/licenses
          
          # 3. Записываем хэши официальных лицензий Google, чтобы sdkmanager считал их принятыми
          echo -e "\n244313f851b6973714464533dfe386091ae672c9" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-license
          echo -e "\n84831b9409646a918e30573bab4c9c91346d8abd" > ~/.buildozer/android/platform/android-sdk/licenses/android-sdk-preview-license
          echo -e "\nde56728758b04cccc85b81c78b547f8848ef2212" > ~/.buildozer/android/platform/android-sdk/licenses/android-googletv-license
          
          # 4. Прокидываем путь к установленному SDK
          export ANDROID_SDK_ROOT=$ANDROID_HOME
          
          # 5. Запускаем сборку
          yes | buildozer -v android debug
        env:
          BUILDOZER_WARN_ON_ROOT: 1
